version: "3.4"
services:
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=challenge
volumes:
  mysql:
    name: mysql
