
# Spring Boot configuration
spring:
# Database
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/challenge
    username: root
    password: password
# JPA properties
  jpa:
    properties:
      hibernate:
        default_schema: public
        formatSql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
# Server configuration
server:
  port: 8080
  servlet:
    context-path: /challenge/api